language: java
jdk: openjdk8


addons:
  sonarcloud:
    organization: "georgeerol"
    token:
      secure: "d52bbcc2439e4630bc1c4b310946a28728019e59" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=georgeerol_ProjectManagementApp
